#spring:
#  datasource:
#    url: jdbc:log4jdbc:oracle:thin:@192.168.0.210:1521:DYDB # 또는 Service Name 형식
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    username: dy_std
#    password: dy_std

spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.113:1521:cimms # 또는 Service Name 형식
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: CIMMS_TOBE
    password: CIMMS_TOBE

logging:
  level:
    org:
      mybatis: DEBUG
      jdbc: DEBUG
      # 추가로 log4jdbc 로그를 위한 설정
    log4jdbc:
      log: DEBUG




